### GET HOME
GET http://localhost:9000/api/products

### GET ONE
GET http://localhost:9000/api/products/1668027669178

### CREATE
POST http://localhost:9000/api/products
Content-Type: application/json

{
   "status": "published",
   "url": "https://world.openfoodfacts.org/product/20221126",
   "creator": "securita",
   "product_name": "Madalenas quadradas",
   "quantity": "380 g (6 x 2 u.)",
   "brands": "La Cestera",
   "categories": "Lanches comida, Lanches doces, Biscoitos e Bolos, Bolos, Madalenas",
   "labels": "Contem gluten, Contém derivados de ovos, Contém ovos",
   "cities": "não sei",
   "purchase_places": "Braga,Portugal",
   "stores": "Lidl",
   "ingredients_text": "farinha de trigo, açúcar, óleo vegetal de girassol, clara de ovo, ovo, humidificante (sorbitol), levedantes químicos (difosfato dissódico, hidrogenocarbonato de sódio), xarope de glucose-frutose, sal, aroma",
   "traces": "Frutos de casca rija,Leite,Soja,Sementes de sésamo,Produtos à base de sementes de sésamo",
   "serving_size": "madalena 31.7 g",
   "serving_quantity": 31.7,
   "nutriscore_score": 17,
   "nutriscore_grade": "d",
   "main_category": "en:madeleines",
   "image_url": "https://static.openfoodfacts.org/images/products/20221126/front_pt.5.400.jpg"
}

### DELETE
DELETE http://localhost:9000/api/products/1668026160997

### UPDATE
PUT http://localhost:9000/api/products/1668026190609
Content-Type: application/json

{
   "status": "published",
   "url": "https://world.openfoodfacts.org/product/20221126",
   "creator": "securita",
   "product_name": "Madalenas quadradas 2",
   "quantity": "380 g (6 x 2 u.)",
   "brands": "La Cestera",
   "categories": "Lanches comida, Lanches doces, Biscoitos e Bolos, Bolos, Madalenas",
   "labels": "Contem gluten, Contém derivados de ovos, Contém ovos",
   "cities": "não sei",
   "purchase_places": "Braga,Portugal",
   "stores": "Lidl",
   "ingredients_text": "farinha de trigo, açúcar, óleo vegetal de girassol, clara de ovo, ovo, humidificante (sorbitol), levedantes químicos (difosfato dissódico, hidrogenocarbonato de sódio), xarope de glucose-frutose, sal, aroma",
   "traces": "Frutos de casca rija,Leite,Soja,Sementes de sésamo,Produtos à base de sementes de sésamo",
   "serving_size": "madalena 31.7 g",
   "serving_quantity": 31.7,
   "nutriscore_score": 17,
   "nutriscore_grade": "d",
   "main_category": "en:madeleines",
   "image_url": "https://static.openfoodfacts.org/images/products/20221126/front_pt.5.400.jpg"
}